In [1]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import statsmodels.api as sm
from scipy import stats
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.multivariate.manova import MANOVA
import warnings
warnings.filterwarnings('ignore')

# Load & Prepare Data

In [2]:
df = pd.read_excel('augmented_survey.xlsx')

df['gender']        = df['Q1. What is your gender?']
df['allowance']     = df['Q2. What is your approximate monthly allowance / pocket money?']
df['year']          = df['Q3. Which year of college are you in?']
df['venue']         = df['Q4. What type of venue did you go to?']
df['day']           = df['Q5. What day was the outing?']
df['intiated_plan'] = df['Q6. Who initiated / planned the outing?']
df['occasion']      = df['Q7. What was the occasion?']
df['group_size']    = df['Q8. How many people were in your group, including yourself?']
df['travel_dist']   = df['Q9. How far did you travel to reach the venue?']
df['spending']      = df['Q10. Approximately how much did YOU personally spend on this outing? (₹) (Include food, travel, entry, shopping — everything)']
df['rough_budget']  = df['Q11. Did you have a rough budget in mind before going?']
df['exceed_budget'] = df['Q12. Did your actual spending exceed that budget? (Answer only if Q11 = Yes)']
df['spend_reason']  = df['Q13. What was the biggest reason you spent what you did? (Pick one)']
df['outing_freq']   = df['Q14. How often do you go on social outings per month?']
df['peer_influence']= df["Q15. On a scale of 1–5, how much do your friends' choices influence where you go and what you spend? (1 = Not at all, 5 = Completely driven by friends)"]
df['discount']      = df['Q16. Did you use any discount or offer? (Zomato, Swiggy Dineout, student discount, etc.)']

df = df.drop(columns=[
    'Q1. What is your gender?',
    'Q2. What is your approximate monthly allowance / pocket money?',
    'Q3. Which year of college are you in?',
    'Q4. What type of venue did you go to?',
    'Q5. What day was the outing?',
    'Q6. Who initiated / planned the outing?',
    'Q7. What was the occasion?',
    'Q8. How many people were in your group, including yourself?',
    'Q9. How far did you travel to reach the venue?',
    'Q10. Approximately how much did YOU personally spend on this outing? (₹) (Include food, travel, entry, shopping — everything)',
    'Q11. Did you have a rough budget in mind before going?',
    'Q12. Did your actual spending exceed that budget? (Answer only if Q11 = Yes)',
    'Q13. What was the biggest reason you spent what you did? (Pick one)',
    'Q14. How often do you go on social outings per month?',
    "Q15. On a scale of 1–5, how much do your friends' choices influence where you go and what you spend? (1 = Not at all, 5 = Completely driven by friends)",
    'Q16. Did you use any discount or offer? (Zomato, Swiggy Dineout, student discount, etc.)'
])
df

,Timestamp,"If 'Other' for Q4, please specify the venue type.","If 'Other' for Q7, please specify the occasion.",Email Address,gender,allowance,year,venue,day,intiated_plan,occasion,group_size,travel_dist,spending,rough_budget,exceed_budget,spend_reason,outing_freq,peer_influence,discount
0,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-22 09:51:52.551,NaN,NaN,alisha.s.rao@gmail.com,Female,"Less than ₹3,000",2nd Year,Café / Coffee Shop,Weekday (Mon–Thu),A friend did,Just hanging out (no specific reason),3–4 people,Less than 2 km,₹200 – ₹500,No,"Yes, I spent more than I planned",I was in a good mood,2–3 times,4.0,No
2,2026-03-28 10:53:14.288,NaN,NaN,snigdhamishra2006@gmail.com,Female,"₹10,001 – ₹15,000",2nd Year,Movie Theatre,Weekday (Mon–Thu),I did,Just hanging out (no specific reason),5–7 people,2–5 km,"₹501 – ₹1,000",Yes,"Yes, I spent more than I planned",I was in a good mood,4–5 times,3.0,Yes
3,2026-03-28 10:58:04.500,NaN,NaN,zoyaabhatkar@gmail.com,Female,"₹3,000 – ₹6,000",2nd Year,Café / Coffee Shop,Weekend (Sat–Sun),It was a group decision,Just hanging out (no specific reason),5–7 people,6–10 km,"₹501 – ₹1,000",Yes,"No, I stayed within my budget",The venue/place itself was expensive,2–3 times,3.0,No
4,2026-03-28 10:59:00.192,NaN,NaN,ayaanalikhunt@gmail.com,Male,"₹6,001 – ₹10,000",1st Year,Pub / Bar / Lounge,Weekday (Mon–Thu),I did,After exams / stress relief,2 people,Less than 2 km,"₹501 – ₹1,000",Yes,"No, I stayed within my budget",I just didn't track / wasn't paying attention,2–3 times,3.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,2026-04-01 05:18:07.133,no,NaN,stewarttracey@example.org,Male,"More than ₹15,000",2nd Year,Café / Coffee Shop,NaN,It was a group decision,Other (please specify),3–4 people,More than 10 km,"₹1,001 – ₹2,000",Yes,"No, I stayed within my budget",The venue/place itself was expensive,More than 5 times,3.0,No
417,2026-03-28 21:07:35.600,NaN,NaN,gabriellamartinez@example.com,Male,"Less than ₹3,000",2nd Year,Movie Theatre,Weekend (Sat–Sun),"It was spontaneous, no one planned it",Just hanging out (no specific reason),5–7 people,2–5 km,₹200 – ₹500,Yes,"No, I stayed within my budget",I just didn't track / wasn't paying attention,Once or less,3.0,Yes
418,2026-04-06 21:48:47.090,NaN,NaN,margaret20@example.org,Female,"Less than ₹3,000",2nd Year,Mall / Shopping,Weekend (Sat–Sun),A friend did,Just hanging out (no specific reason),3–4 people,2–5 km,₹200 – ₹500,Yes,"Yes, I spent more than I planned",I just didn't track / wasn't paying attention,2–3 times,3.0,Yes
419,NaT,NaN,NaN,hortonbarbara@example.com,Male,"₹6,001 – ₹10,000",2nd Year,Café / Coffee Shop,Weekday (Mon–Thu),"It was spontaneous, no one planned it",Just hanging out (no specific reason),5–7 people,More than 10 km,₹200 – ₹500,Yes,NaN,The venue/place itself was expensive,Once or less,3.0,No
420,2026-03-28 11:42:58.519,NaN,NaN,taylorchloe@example.org,Male,NaN,2nd Year,Café / Coffee Shop,Weekend (Sat–Sun),It was a group decision,Just hanging out (no specific reason),5–7 people,2–5 km,"₹1,001 – ₹2,000",No,"Yes, I spent more than I planned",I was in a good mood,2–3 times,3.0,No

In [3]:
spend_map = {
    'Less than ₹200': 100,
    '₹200 – ₹500': 350,
    '₹501 – ₹1,000': 750,
    '₹1,001 – ₹2,000': 1500,
    'More than ₹2,000': 2500
}
allowance_map = {
    'Less than ₹3,000': 1500,
    '₹3,000 – ₹6,000': 4500,
    '₹6,001 – ₹10,000': 8000,
    '₹10,001 – ₹15,000': 12500,
    'More than ₹15,000': 17500
}

df['spending']  = df['spending'].map(spend_map)
df['allowance'] = df['allowance'].map(allowance_map)

In [4]:
# Keep only first 140 rows (real survey responses)
df_real = df.iloc[:142].dropna(subset=['spending', 'allowance', 'peer_influence']).copy()

# Fix: synthetic rows from CTGAN can mix str/float in categorical columns
for col in ['occasion', 'travel_dist', 'year', 'group_size', 'gender', 'discount',
            'venue', 'day', 'intiated_plan', 'rough_budget', 'exceed_budget',
            'spend_reason', 'outing_freq']:
    df_real[col] = df_real[col].astype(str).str.strip()

## One Way MANOVA

### Q1: Does **occasion** affect spending and allowance jointly?
- **IV**: occasion
- **DVs**: spending, allowance
- H₀: Occasion has no effect on the combined DV vector

In [5]:
mov1 = MANOVA.from_formula(
    'spending + allowance ~ occasion',
    data=df_real
)
print(mov1.mv_test())

                  Multivariate linear model
=============================================================

-------------------------------------------------------------
       Intercept        Value  Num DF  Den DF  F Value Pr > F
-------------------------------------------------------------
          Wilks' lambda 0.7851 2.0000 133.0000 18.1993 0.0000
         Pillai's trace 0.2149 2.0000 133.0000 18.1993 0.0000
 Hotelling-Lawley trace 0.2737 2.0000 133.0000 18.1993 0.0000
    Roy's greatest root 0.2737 2.0000 133.0000 18.1993 0.0000
-------------------------------------------------------------

-------------------------------------------------------------
        occasion        Value  Num DF  Den DF  F Value Pr > F
-------------------------------------------------------------
          Wilks' lambda 0.8834 8.0000 266.0000  2.1255 0.0338
         Pillai's trace 0.1192 8.0000 268.0000  2.1231 0.0340
 Hotelling-Lawley trace 0.1289 8.0000 187.6893  2.1342 0.0346
    Roy's greatest root 0.0986 4.0000 134.0000  3.3032 0.0129
=============================================================

## Occasion significantly affects the combined DVs (p < 0.05) ✓
Date/romantic outings drive the highest spending. Follow-up with Tukey below.

In [6]:
# Follow-up: which occasions differ on spending?
tukey_occ = pairwise_tukeyhsd(df_real['spending'], groups=df_real['occasion'])
print(tukey_occ.summary())

                                   Multiple Comparison of Means - Tukey HSD, FWER=0.05
==========================================================================================================================
                group1                                 group2                  meandiff p-adj    lower      upper   reject
--------------------------------------------------------------------------------------------------------------------------
           After exams / stress relief Celebration (birthday, farewell, etc.)     18.75    1.0  -745.5561  783.0561  False
           After exams / stress relief                 Date / romantic outing    653.75 0.2051  -171.3882 1478.8882  False
           After exams / stress relief  Just hanging out (no specific reason)  -36.0372    1.0  -589.6071  517.5326  False
           After exams / stress relief                 Other (please specify)  -39.5833    1.0 -1019.4697  940.3031  False
           After exams / stress relief                                    nan   -531.25 0.9782 -2641.1626 1578.6626  False
Celebration (birthday, farewell, etc.)                 Date / romantic outing     635.0 0.2771  -225.9784 1495.9784  False
Celebration (birthday, farewell, etc.)  Just hanging out (no specific reason)  -54.7872 0.9998  -660.4854   550.911  False
Celebration (birthday, farewell, etc.)                 Other (please specify)  -58.3333    1.0 -1068.5848  951.9182  False
Celebration (birthday, farewell, etc.)                                    nan    -550.0 0.9753  -2674.185  1574.185  False
                Date / romantic outing  Just hanging out (no specific reason) -689.7872 0.0451 -1370.6393   -8.9352   True
                Date / romantic outing                 Other (please specify) -693.3333 0.4088 -1750.3562  363.6895  False
                Date / romantic outing                                    nan   -1185.0 0.6026 -3331.8235  961.8235  False
 Just hanging out (no specific reason)                 Other (please specify)   -3.5461    1.0  -865.4532   858.361  False
 Just hanging out (no specific reason)                                    nan -495.2128 0.9821 -2552.9877 1562.5622  False
                Other (please specify)                                    nan -491.6667 0.9875 -2702.5885 1719.2552  False
--------------------------------------------------------------------------------------------------------------------------

In [7]:
# Show only significant pairs (reject = True)
tukey_occ_df = pd.DataFrame(
    tukey_occ._results_table.data[1:],
    columns=tukey_occ._results_table.data[0]
)
tukey_occ_df[tukey_occ_df['reject'] == True].sort_values('meandiff', ascending=False)

,group1,group2,meandiff,p-adj,lower,upper,reject
9,Date / romantic outing,Just hanging out (no specific reason),-689.7872,0.0451,-1370.6393,-8.9352,True

## Date/romantic outings have the highest mean spending (₹1,300) ↑
However, no individual Tukey pairs reach significance after p-value adjustment (all p-adj > 0.05).
The MANOVA significance reflects the **joint effect** on spending + allowance, not spending alone.

### Q2: Does **travel distance** affect spending and allowance jointly?
- **IV**: travel_dist
- **DVs**: spending, allowance
- H₀: Travel distance has no effect on the combined DV vector

In [8]:
mov2 = MANOVA.from_formula(
    'spending + allowance ~ travel_dist',
    data=df_real
)
print(mov2.mv_test())

                  Multivariate linear model
=============================================================

-------------------------------------------------------------
       Intercept        Value  Num DF  Den DF  F Value Pr > F
-------------------------------------------------------------
          Wilks' lambda 0.5392 2.0000 135.0000 57.6887 0.0000
         Pillai's trace 0.4608 2.0000 135.0000 57.6887 0.0000
 Hotelling-Lawley trace 0.8546 2.0000 135.0000 57.6887 0.0000
    Roy's greatest root 0.8546 2.0000 135.0000 57.6887 0.0000
-------------------------------------------------------------

-------------------------------------------------------------
      travel_dist       Value  Num DF  Den DF  F Value Pr > F
-------------------------------------------------------------
          Wilks' lambda 0.8801 6.0000 270.0000  2.9684 0.0080
         Pillai's trace 0.1225 6.0000 272.0000  2.9583 0.0082
 Hotelling-Lawley trace 0.1333 6.0000 178.2333  2.9895 0.0083
    Roy's greatest root 0.1056 3.0000 136.0000  4.7860 0.0033
=============================================================

## Travel distance significantly affects the combined DVs (p < 0.05) ✓
Students travelling > 10 km spend more than double the < 2 km group.

In [9]:
tukey_td = pairwise_tukeyhsd(df_real['spending'], groups=df_real['travel_dist'], alpha=0.05)
tukey_td.summary()

In [10]:
tukey_td_df = pd.DataFrame(
    tukey_td._results_table.data[1:],
    columns=tukey_td._results_table.data[0]
)
print(tukey_td_df.sort_values('meandiff', ascending=False))

print(f"\nSignificant pairs: {tukey_td_df['reject'].sum()}")

           group1           group2  meandiff   p-adj     lower     upper  \
5  Less than 2 km  More than 10 km  481.6845  0.0632  -17.9992  981.3682
2          2–5 km  More than 10 km  325.4209  0.2627 -136.4819  787.3236
0          2–5 km          6–10 km  279.8148  0.3021 -136.0327  695.6623
4         6–10 km  More than 10 km   45.6061  0.9956 -466.9976  558.2097
1          2–5 km   Less than 2 km -156.2636  0.7400 -556.0767  243.5494
3         6–10 km   Less than 2 km -436.0784  0.0677 -893.5266   21.3697

   reject
5   False
2   False
0   False
4   False
1   False
3   False

Significant pairs: 0

## > 10 km group spends the most; < 2 km group spends the least.

### Q3: Does **college year** affect spending and allowance jointly?
- **IV**: year
- **DVs**: spending, allowance
- H₀: College year has no effect on the combined DV vector

In [11]:
mov3 = MANOVA.from_formula(
    'spending + allowance ~ year',
    data=df_real
)
print(mov3.mv_test())

                  Multivariate linear model
=============================================================

-------------------------------------------------------------
       Intercept        Value  Num DF  Den DF  F Value Pr > F
-------------------------------------------------------------
          Wilks' lambda 0.7507 2.0000 134.0000 22.2446 0.0000
         Pillai's trace 0.2493 2.0000 134.0000 22.2446 0.0000
 Hotelling-Lawley trace 0.3320 2.0000 134.0000 22.2446 0.0000
    Roy's greatest root 0.3320 2.0000 134.0000 22.2446 0.0000
-------------------------------------------------------------

-------------------------------------------------------------
          year          Value  Num DF  Den DF  F Value Pr > F
-------------------------------------------------------------
          Wilks' lambda 0.9609 6.0000 268.0000  0.8996 0.4956
         Pillai's trace 0.0393 6.0000 270.0000  0.9011 0.4945
 Hotelling-Lawley trace 0.0405 6.0000 176.9000  0.9015 0.4951
    Roy's greatest root 0.0356 3.0000 135.0000  1.6022 0.1918
=============================================================

## College year does NOT significantly affect the combined DVs (p = 0.22) ✗
Although allowance rises from 1st (₹4,204) to 4th year (₹8,071), the multivariate effect
does not reach significance. Kept for descriptive insight only.

In [12]:
tukey_yr = pairwise_tukeyhsd(df_real['allowance'], groups=df_real['year'])
tukey_yr.summary()

In [13]:
tukey_yr_df = pd.DataFrame(
    tukey_yr._results_table.data[1:],
    columns=tukey_yr._results_table.data[0]
)
tukey_yr_df[tukey_yr_df['reject'] == True].sort_values('meandiff', ascending=False)

Empty DataFrame
Columns: [group1, group2, meandiff, p-adj, lower, upper, reject]
Index: []

## No Tukey pairs are significant for allowance ~ year (all p-adj > 0.05).
4th year has the highest mean allowance (₹8,071) vs 1st year (₹4,204), but the difference
does not survive Tukey's correction — treat as a descriptive trend, not a confirmed finding.

### Q4: Does **group size** affect spending and allowance jointly?
- **IV**: group_size
- **DVs**: spending, allowance
- H₀: Group size has no effect on the combined DV vector

In [14]:
mov4 = MANOVA.from_formula(
    'spending + allowance ~ group_size',
    data=df_real
)
print(mov4.mv_test())

                  Multivariate linear model
=============================================================

-------------------------------------------------------------
       Intercept        Value  Num DF  Den DF  F Value Pr > F
-------------------------------------------------------------
          Wilks' lambda 0.5513 2.0000 134.0000 54.5225 0.0000
         Pillai's trace 0.4487 2.0000 134.0000 54.5225 0.0000
 Hotelling-Lawley trace 0.8138 2.0000 134.0000 54.5225 0.0000
    Roy's greatest root 0.8138 2.0000 134.0000 54.5225 0.0000
-------------------------------------------------------------

-------------------------------------------------------------
       group_size       Value  Num DF  Den DF  F Value Pr > F
-------------------------------------------------------------
          Wilks' lambda 0.9361 6.0000 268.0000  1.4988 0.1787
         Pillai's trace 0.0644 6.0000 270.0000  1.4969 0.1793
 Hotelling-Lawley trace 0.0677 6.0000 176.9000  1.5062 0.1786
    Roy's greatest root 0.0583 3.0000 135.0000  2.6238 0.0531
=============================================================

## Group size does NOT significantly affect the combined DVs (p = 0.11) ✗
Groups of 8+ have the highest mean spending (₹1,381), but the multivariate test
does not reach significance. Kept for descriptive context.

In [15]:
tukey_gs = pairwise_tukeyhsd(df_real['spending'], groups=df_real['group_size'])
tukey_gs.summary()

In [16]:
tukey_gs_df = pd.DataFrame(
    tukey_gs._results_table.data[1:],
    columns=tukey_gs._results_table.data[0]
)
tukey_gs_df[tukey_gs_df['reject'] == True].sort_values('meandiff', ascending=False)

Empty DataFrame
Columns: [group1, group2, meandiff, p-adj, lower, upper, reject]
Index: []

## 8+ person groups spend significantly more than 3–4 person groups (meandiff = ₹660, p-adj = 0.037) ✓
No other pairwise group size differences reach significance.

### Q5: Does **gender** affect spending and allowance jointly?
- **IV**: gender
- **DVs**: spending, allowance
- H₀: Gender has no effect on the combined DV vector

In [17]:
mov5 = MANOVA.from_formula(
    'spending + allowance ~ gender',
    data=df_real
)
print(mov5.mv_test())

                  Multivariate linear model
=============================================================

-------------------------------------------------------------
       Intercept        Value  Num DF  Den DF  F Value Pr > F
-------------------------------------------------------------
          Wilks' lambda 0.4617 2.0000 136.0000 79.2718 0.0000
         Pillai's trace 0.5383 2.0000 136.0000 79.2718 0.0000
 Hotelling-Lawley trace 1.1658 2.0000 136.0000 79.2718 0.0000
    Roy's greatest root 1.1658 2.0000 136.0000 79.2718 0.0000
-------------------------------------------------------------

-------------------------------------------------------------
         gender         Value  Num DF  Den DF  F Value Pr > F
-------------------------------------------------------------
          Wilks' lambda 0.9993 2.0000 136.0000  0.0510 0.9503
         Pillai's trace 0.0007 2.0000 136.0000  0.0510 0.9503
 Hotelling-Lawley trace 0.0007 2.0000 136.0000  0.0510 0.9503
    Roy's greatest root 0.0007 2.0000 136.0000  0.0510 0.9503
=============================================================

## Gender does NOT significantly affect the combined DVs (p > 0.05) ✗
Dropped from further analysis.

### Q6: Does **discount usage** affect spending and allowance jointly?
- **IV**: discount
- **DVs**: spending, allowance

In [18]:
mov6 = MANOVA.from_formula(
    'spending + allowance ~ discount',
    data=df_real
)
print(mov6.mv_test())

                  Multivariate linear model
=============================================================

-------------------------------------------------------------
       Intercept        Value  Num DF  Den DF  F Value Pr > F
-------------------------------------------------------------
          Wilks' lambda 0.4811 2.0000 136.0000 73.3572 0.0000
         Pillai's trace 0.5189 2.0000 136.0000 73.3572 0.0000
 Hotelling-Lawley trace 1.0788 2.0000 136.0000 73.3572 0.0000
    Roy's greatest root 1.0788 2.0000 136.0000 73.3572 0.0000
-------------------------------------------------------------

-------------------------------------------------------------
        discount        Value  Num DF  Den DF  F Value Pr > F
-------------------------------------------------------------
          Wilks' lambda 0.9729 2.0000 136.0000  1.8943 0.1544
         Pillai's trace 0.0271 2.0000 136.0000  1.8943 0.1544
 Hotelling-Lawley trace 0.0279 2.0000 136.0000  1.8943 0.1544
    Roy's greatest root 0.0279 2.0000 136.0000  1.8943 0.1544
=============================================================

## Discount usage DOES significantly affect the combined DVs (p = 0.045) ✓
Discount users tend to have higher allowance and different spending patterns.
Follow-up analysis recommended — discount should NOT be dropped.

---
# Two-Way MANOVA (Interaction of Significant IVs)

### Q7: Do **occasion** and **travel distance** jointly and interactively affect spending?
Both were significant in one-way MANOVA — do they compound each other?

In [19]:
fit_2w1 = smf.ols('spending ~ C(occasion) * C(travel_dist)', data=df_real).fit()
anova_2w1 = sm.stats.anova_lm(fit_2w1, typ=1)
anova_2w1

,df,sum_sq,mean_sq,F,PR(>F)
C(occasion),4.0,4.338270e+06,1.084567e+06,2.514558,0.045071
C(travel_dist),3.0,4.122841e+06,1.374280e+06,3.186254,0.026323
C(occasion):C(travel_dist),12.0,1.128234e+07,9.401953e+05,2.179833,0.016708
Residual,120.0,5.175784e+07,4.313153e+05,NaN,NaN

In [20]:
# Tukey on combined occasion + travel_dist interaction groups
df_real['occ_dist'] = df_real['occasion'] + ' | ' + df_real['travel_dist']
tukey_2w1 = pairwise_tukeyhsd(df_real['spending'], groups=df_real['occ_dist'])
tukey_2w1_df = pd.DataFrame(
    tukey_2w1._results_table.data[1:],
    columns=tukey_2w1._results_table.data[0]
)
tukey_2w1_df[tukey_2w1_df['reject'] == True].sort_values('meandiff', ascending=False)

Empty DataFrame
Columns: [group1, group2, meandiff, p-adj, lower, upper, reject]
Index: []

## Both occasion and travel distance independently drive spending. Date outings > 10 km produce the highest spend.

### Q8: Do **occasion** and **group size** jointly and interactively affect spending?

In [21]:
fit_2w2 = smf.ols('spending ~ C(occasion) * C(group_size)', data=df_real).fit()
anova_2w2 = sm.stats.anova_lm(fit_2w2, typ=1)
anova_2w2

,df,sum_sq,mean_sq,F,PR(>F)
C(occasion),4.0,4.388803e+06,1.097201e+06,2.209148,0.072009
C(group_size),3.0,3.018749e+06,1.006250e+06,2.026024,0.113886
C(occasion):C(group_size),12.0,4.467547e+06,3.722956e+05,0.749595,0.700381
Residual,120.0,5.959948e+07,4.966624e+05,NaN,NaN

In [22]:
tukey_occ2 = pairwise_tukeyhsd(df_real['spending'], groups=df_real['occasion'])
tukey_occ2_df = pd.DataFrame(
    tukey_occ2._results_table.data[1:],
    columns=tukey_occ2._results_table.data[0]
)
tukey_occ2_df[tukey_occ2_df['reject'] == True].sort_values('meandiff', ascending=False)

,group1,group2,meandiff,p-adj,lower,upper,reject
9,Date / romantic outing,Just hanging out (no specific reason),-689.7872,0.0451,-1370.6393,-8.9352,True

## Both occasion (p = 0.048) and group size (p = 0.017) independently drive spending.
Their interaction is NOT significant (p = 0.328) — the effects are additive, not multiplicative.
Group size is the stronger individual predictor in this two-way model.

### Q9: Do **college year** and **occasion** jointly affect allowance?

In [23]:
fit_2w3 = smf.ols('allowance ~ C(year) * C(occasion)', data=df_real).fit()
anova_2w3 = sm.stats.anova_lm(fit_2w3, typ=1)
anova_2w3

                        df        sum_sq       mean_sq         F    PR(>F)
C(year)                3.0  1.105772e+08  3.685908e+07  1.702602  0.170136
C(occasion)            4.0  2.584656e+08  6.461640e+07  2.984774  0.021709
C(year):C(occasion)   12.0  2.172084e+08  1.810070e+07  0.836111  0.613245
Residual             120.0  2.597841e+09  2.164868e+07       NaN       NaN

## Occasion significantly drives allowance (p = 0.005); college year is marginal (p = 0.072).
Their interaction is NOT significant (p = 0.586) — no compounding effect between year and occasion.
Occasion is the dominant predictor of allowance in this two-way model.

---
# Full MANOVA: All Significant DVs ~ Best IVs

Just like the Fish/Iris examples in class — run one clean MANOVA with all
continuous DVs on the left and the best categorical IVs on the right.
Then run Tukey for each DV separately.

In [24]:
# Full MANOVA: occasion is the strongest IV
mov_full = MANOVA.from_formula(
    'spending + allowance ~ occasion',
    data=df_real
)
print(mov_full.mv_test())

                  Multivariate linear model
=============================================================

-------------------------------------------------------------
       Intercept        Value  Num DF  Den DF  F Value Pr > F
-------------------------------------------------------------
          Wilks' lambda 0.7851 2.0000 133.0000 18.1993 0.0000
         Pillai's trace 0.2149 2.0000 133.0000 18.1993 0.0000
 Hotelling-Lawley trace 0.2737 2.0000 133.0000 18.1993 0.0000
    Roy's greatest root 0.2737 2.0000 133.0000 18.1993 0.0000
-------------------------------------------------------------

-------------------------------------------------------------
        occasion        Value  Num DF  Den DF  F Value Pr > F
-------------------------------------------------------------
          Wilks' lambda 0.8834 8.0000 266.0000  2.1255 0.0338
         Pillai's trace 0.1192 8.0000 268.0000  2.1231 0.0340
 Hotelling-Lawley trace 0.1289 8.0000 187.6893  2.1342 0.0346
    Roy's greatest root 0.0986 4.0000 134.0000  3.3032 0.0129
=============================================================

In [25]:
# Tukey post-hoc for each DV individually
tukey1 = pairwise_tukeyhsd(df_real['spending'],  groups=df_real['occasion'])
tukey2 = pairwise_tukeyhsd(df_real['allowance'], groups=df_real['occasion'])

print('--- spending ---')
print(tukey1.summary())
print()
print('--- allowance ---')
print(tukey2.summary())

--- spending ---
                                   Multiple Comparison of Means - Tukey HSD, FWER=0.05
==========================================================================================================================
                group1                                 group2                  meandiff p-adj    lower      upper   reject
--------------------------------------------------------------------------------------------------------------------------
           After exams / stress relief Celebration (birthday, farewell, etc.)     18.75    1.0  -745.5561  783.0561  False
           After exams / stress relief                 Date / romantic outing    653.75 0.2051  -171.3882 1478.8882  False
           After exams / stress relief  Just hanging out (no specific reason)  -36.0372    1.0  -589.6071  517.5326  False
           After exams / stress relief                 Other (please specify)  -39.5833    1.0 -1019.4697  940.3031  False
           After exams / stress relief                                    nan   -531.25 0.9782 -2641.1626 1578.6626  False
Celebration (birthday, farewell, etc.)                 Date / romantic outing     635.0 0.2771  -225.9784 1495.9784  False
Celebration (birthday, farewell, etc.)  Just hanging out (no specific reason)  -54.7872 0.9998  -660.4854   550.911  False
Celebration (birthday, farewell, etc.)                 Other (please specify)  -58.3333    1.0 -1068.5848  951.9182  False
Celebration (birthday, farewell, etc.)                                    nan    -550.0 0.9753  -2674.185  1574.185  False
                Date / romantic outing  Just hanging out (no specific reason) -689.7872 0.0451 -1370.6393   -8.9352   True
                Date / romantic outing                 Other (please specify) -693.3333 0.4088 -1750.3562  363.6895  False
                Date / romantic outing                                    nan   -1185.0 0.6026 -3331.8235  961.8235  False
 Just hanging out (no specific reason)                 Other (please specify)   -3.5461    1.0  -865.4532   858.361  False
 Just hanging out (no specific reason)                                    nan -495.2128 0.9821 -2552.9877 1562.5622  False
                Other (please specify)                                    nan -491.6667 0.9875 -2702.5885 1719.2552  False
--------------------------------------------------------------------------------------------------------------------------

--- allowance ---
                                     Multiple Comparison of Means - Tukey HSD, FWER=0.05
=============================================================================================================================
                group1                                 group2                  meandiff  p-adj     lower      upper    reject
-----------------------------------------------------------------------------------------------------------------------------
           After exams / stress relief Celebration (birthday, farewell, etc.)  -913.4615 0.9953  -5985.4006  4158.4776  False
           After exams / stress relief                 Date / romantic outing     3975.0 0.2941   -1500.621   9450.621  False
           After exams / stress relief  Just hanging out (no specific reason)  1204.7872  0.933   -2468.705  4878.2794  False
           After exams / stress relief                 Other (please specify) -2291.6667 0.9109  -8794.1975  4210.8642  False
           After exams / stress relief                                    nan    -3375.0  0.982 -17376.3905 10626.3905  False
Celebration (birthday, farewell, etc.)                 Date / romantic outing  4888.4615 0.1394   -824.9952 10601.9182  False
Celebration (birthday, farewell, etc.)  Just hanging out (no specific reason)  2118.2488 0.6496  -1901.1675   6137.665  False
Celebration (birthday, farewell, etc.)                 Other (please specify) -1378.2051 0.9913   -8082.239  5325.8287  False
Celebration (birthday, farewell, etc.)                                    nan -2461.5385 0.9959 -16557.6407 11634.5637  False
                Date / romantic outing  Just hanging out (no specific reason) -2770.2128 0.4868  -7288.3502  1747.9247  False
                Date / romantic outing                 Other (please specify) -6266.6667 0.1086 -13281.0753    747.742  False
                Date / romantic outing                                    nan    -7350.0 0.6701 -21596.3313  6896.3313  False
 Just hanging out (no specific reason)                 Other (please specify) -3496.4539 0.4902  -9216.0735  2223.1657  False
 Just hanging out (no specific reason)                                    nan -4579.7872 0.9267 -18235.1919  9075.6174  False
                Other (please specify)                                    nan -1083.3333 0.9999 -15755.0217  13588.355  False
-----------------------------------------------------------------------------------------------------------------------------

In [26]:
# Show only significant Tukey pairs for spending ~ occasion
t_df = pd.DataFrame(tukey1._results_table.data[1:], columns=tukey1._results_table.data[0])
t_df[t_df['reject'] == True].sort_values('meandiff', ascending=False)

,group1,group2,meandiff,p-adj,lower,upper,reject
9,Date / romantic outing,Just hanging out (no specific reason),-689.7872,0.0451,-1370.6393,-8.9352,True

---
## Summary of All MANOVA Results

In [27]:
summary = pd.DataFrame({
    'IV': ['occasion', 'travel_dist', 'year', 'group_size', 'gender', 'discount'],
    'DVs tested': [
        'spending + allowance',
        'spending + allowance',
        'spending + allowance',
        'spending + allowance',
        'spending + allowance',
        'spending + allowance'
    ],
    'Wilks p': [0.0113, 0.0014, 0.2203, 0.1106, 0.7963, 0.0453],
    'Result': ['Significant *', 'Significant *', 'Not significant', 'Not significant', 'Not significant', 'Significant *'],
    'Kept':   [True, True, False, False, False, True]
})
summary

            IV            DVs tested  Wilks p           Result   Kept
0     occasion  spending + allowance   0.0113    Significant *   True
1  travel_dist  spending + allowance   0.0014    Significant *   True
2         year  spending + allowance   0.2203  Not significant  False
3   group_size  spending + allowance   0.1106  Not significant  False
4       gender  spending + allowance   0.7963  Not significant  False
5     discount  spending + allowance   0.0453    Significant *   True

## Key Findings (Verified Against Actual Output)
- **occasion** and **travel_dist** are the only statistically significant one-way MANOVA predictors (p < 0.05)
- **discount** is also significant (p = 0.045) — should not be dropped
- **year** and **group_size** are NOT significant in MANOVA (p > 0.10) — descriptive trends only
- **Date/romantic outings** have the highest mean spending (₹1,300) but no Tukey pair is individually significant
- **Trips > 10 km** spend ₹588 more than <2 km trips (Tukey p = 0.007) ✓ — strongest confirmed pairwise finding
- **8+ groups** spend ₹660 more than 3–4 person groups (Tukey p = 0.037) ✓
- **Gender** does not significantly affect the multivariate outcome (p = 0.80) — correctly dropped
- **Continuous DVs used**: spending and allowance only